/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-codegen.sh

// AUTO-GENERATED FUNCTIONS START HERE. DO NOT EDIT.
var map_LifecycleEvent = map[string]string{
	"":       "LifecycleEvent represents a binding between a LifecycleTransition and the Kubelet/Driver responsible for executing it.",
	"spec":   "Spec defines the binding parameters for claiming a transition.",
	"status": "Status reports the current state of the transition claim.",
}

func (LifecycleEvent) SwaggerDoc() map[string]string {
	return map_LifecycleEvent
}

var map_LifecycleEventList = map[string]string{
	"": "LifecycleEventList contains a list of LifecycleEvent resources.",
}

func (LifecycleEventList) SwaggerDoc() map[string]string {
	return map_LifecycleEventList
}

var map_LifecycleEventSpec = map[string]string{
	"":               "LifecycleEventSpec defines the binding parameters to claim a transition.",
	"transitionName": "transitionName refers to a LifecycleTransition object by name.",
	"bindingNode":    "bindingNode identifies a specific Node whose Kubelet can claim the event.",
}

func (LifecycleEventSpec) SwaggerDoc() map[string]string {
	return map_LifecycleEventSpec
}

var map_LifecycleEventStatus = map[string]string{
	"":            "LifecycleEventStatus reports the current state of the transition claim.",
	"claimStatus": "claimStatus represents the current phase of the event's lifecycle.",
	"driver":      "driver is a copy of the driver name from the LifecycleTransition.",
	"sla":         "sla specifies the deadline by which the transition must complete.",
}

func (LifecycleEventStatus) SwaggerDoc() map[string]string {
	return map_LifecycleEventStatus
}

var map_LifecycleTransition = map[string]string{
	"":     "LifecycleTransition defines the desired intent for a Kubernetes resource to undergo a lifecycle change.",
	"spec": "Spec defines the desired lifecycle transition.",
}

func (LifecycleTransition) SwaggerDoc() map[string]string {
	return map_LifecycleTransition
}

var map_LifecycleTransitionList = map[string]string{
	"": "LifecycleTransitionList contains a list of LifecycleTransition resources.",
}

func (LifecycleTransitionList) SwaggerDoc() map[string]string {
	return map_LifecycleTransitionList
}

var map_LifecycleTransitionSpec = map[string]string{
	"":             "LifecycleTransitionSpec describes the parameters of a lifecycle transition.",
	"start":        "start identifies the initial state of the lifecycle transition.",
	"end":          "end identifies the desired terminal state of the lifecycle transition.",
	"nodeName":     "nodeName identifies the specific Node that has a Driver capable of reconciling the LifecycleTransition.",
	"nodeSelector": "nodeSelector defines which Nodes have Drivers capable of reconciling the LifecycleTransition.",
	"allNodes":     "allNodes indicates that all Nodes are capable of reconciling the LifecycleTransition.",
	"sla":          "sla specifies the duration by which the transition from Start to End must be completed.",
	"driver":       "driver specifies the unique identifier of the lifecycle driver responsible for reconciling this transition.",
}

func (LifecycleTransitionSpec) SwaggerDoc() map[string]string {
	return map_LifecycleTransitionSpec
}

// AUTO-GENERATED FUNCTIONS END HERE
