//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	corev1 "k8s.io/api/core/v1"
	lifecyclev1alpha1 "k8s.io/api/lifecycle/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	core "k8s.io/kubernetes/pkg/apis/core"
	lifecycle "k8s.io/kubernetes/pkg/apis/lifecycle"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*lifecyclev1alpha1.LifecycleEvent)(nil), (*lifecycle.LifecycleEvent)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LifecycleEvent_To_lifecycle_LifecycleEvent(a.(*lifecyclev1alpha1.LifecycleEvent), b.(*lifecycle.LifecycleEvent), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*lifecycle.LifecycleEvent)(nil), (*lifecyclev1alpha1.LifecycleEvent)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_lifecycle_LifecycleEvent_To_v1alpha1_LifecycleEvent(a.(*lifecycle.LifecycleEvent), b.(*lifecyclev1alpha1.LifecycleEvent), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*lifecyclev1alpha1.LifecycleEventList)(nil), (*lifecycle.LifecycleEventList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LifecycleEventList_To_lifecycle_LifecycleEventList(a.(*lifecyclev1alpha1.LifecycleEventList), b.(*lifecycle.LifecycleEventList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*lifecycle.LifecycleEventList)(nil), (*lifecyclev1alpha1.LifecycleEventList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_lifecycle_LifecycleEventList_To_v1alpha1_LifecycleEventList(a.(*lifecycle.LifecycleEventList), b.(*lifecyclev1alpha1.LifecycleEventList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*lifecyclev1alpha1.LifecycleEventSpec)(nil), (*lifecycle.LifecycleEventSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LifecycleEventSpec_To_lifecycle_LifecycleEventSpec(a.(*lifecyclev1alpha1.LifecycleEventSpec), b.(*lifecycle.LifecycleEventSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*lifecycle.LifecycleEventSpec)(nil), (*lifecyclev1alpha1.LifecycleEventSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_lifecycle_LifecycleEventSpec_To_v1alpha1_LifecycleEventSpec(a.(*lifecycle.LifecycleEventSpec), b.(*lifecyclev1alpha1.LifecycleEventSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*lifecyclev1alpha1.LifecycleEventStatus)(nil), (*lifecycle.LifecycleEventStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LifecycleEventStatus_To_lifecycle_LifecycleEventStatus(a.(*lifecyclev1alpha1.LifecycleEventStatus), b.(*lifecycle.LifecycleEventStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*lifecycle.LifecycleEventStatus)(nil), (*lifecyclev1alpha1.LifecycleEventStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_lifecycle_LifecycleEventStatus_To_v1alpha1_LifecycleEventStatus(a.(*lifecycle.LifecycleEventStatus), b.(*lifecyclev1alpha1.LifecycleEventStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*lifecyclev1alpha1.LifecycleTransition)(nil), (*lifecycle.LifecycleTransition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LifecycleTransition_To_lifecycle_LifecycleTransition(a.(*lifecyclev1alpha1.LifecycleTransition), b.(*lifecycle.LifecycleTransition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*lifecycle.LifecycleTransition)(nil), (*lifecyclev1alpha1.LifecycleTransition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_lifecycle_LifecycleTransition_To_v1alpha1_LifecycleTransition(a.(*lifecycle.LifecycleTransition), b.(*lifecyclev1alpha1.LifecycleTransition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*lifecyclev1alpha1.LifecycleTransitionList)(nil), (*lifecycle.LifecycleTransitionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LifecycleTransitionList_To_lifecycle_LifecycleTransitionList(a.(*lifecyclev1alpha1.LifecycleTransitionList), b.(*lifecycle.LifecycleTransitionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*lifecycle.LifecycleTransitionList)(nil), (*lifecyclev1alpha1.LifecycleTransitionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_lifecycle_LifecycleTransitionList_To_v1alpha1_LifecycleTransitionList(a.(*lifecycle.LifecycleTransitionList), b.(*lifecyclev1alpha1.LifecycleTransitionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*lifecyclev1alpha1.LifecycleTransitionSpec)(nil), (*lifecycle.LifecycleTransitionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LifecycleTransitionSpec_To_lifecycle_LifecycleTransitionSpec(a.(*lifecyclev1alpha1.LifecycleTransitionSpec), b.(*lifecycle.LifecycleTransitionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*lifecycle.LifecycleTransitionSpec)(nil), (*lifecyclev1alpha1.LifecycleTransitionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_lifecycle_LifecycleTransitionSpec_To_v1alpha1_LifecycleTransitionSpec(a.(*lifecycle.LifecycleTransitionSpec), b.(*lifecyclev1alpha1.LifecycleTransitionSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_LifecycleEvent_To_lifecycle_LifecycleEvent(in *lifecyclev1alpha1.LifecycleEvent, out *lifecycle.LifecycleEvent, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_LifecycleEventSpec_To_lifecycle_LifecycleEventSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_LifecycleEventStatus_To_lifecycle_LifecycleEventStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_LifecycleEvent_To_lifecycle_LifecycleEvent is an autogenerated conversion function.
func Convert_v1alpha1_LifecycleEvent_To_lifecycle_LifecycleEvent(in *lifecyclev1alpha1.LifecycleEvent, out *lifecycle.LifecycleEvent, s conversion.Scope) error {
	return autoConvert_v1alpha1_LifecycleEvent_To_lifecycle_LifecycleEvent(in, out, s)
}

func autoConvert_lifecycle_LifecycleEvent_To_v1alpha1_LifecycleEvent(in *lifecycle.LifecycleEvent, out *lifecyclev1alpha1.LifecycleEvent, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_lifecycle_LifecycleEventSpec_To_v1alpha1_LifecycleEventSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_lifecycle_LifecycleEventStatus_To_v1alpha1_LifecycleEventStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_lifecycle_LifecycleEvent_To_v1alpha1_LifecycleEvent is an autogenerated conversion function.
func Convert_lifecycle_LifecycleEvent_To_v1alpha1_LifecycleEvent(in *lifecycle.LifecycleEvent, out *lifecyclev1alpha1.LifecycleEvent, s conversion.Scope) error {
	return autoConvert_lifecycle_LifecycleEvent_To_v1alpha1_LifecycleEvent(in, out, s)
}

func autoConvert_v1alpha1_LifecycleEventList_To_lifecycle_LifecycleEventList(in *lifecyclev1alpha1.LifecycleEventList, out *lifecycle.LifecycleEventList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]lifecycle.LifecycleEvent)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_LifecycleEventList_To_lifecycle_LifecycleEventList is an autogenerated conversion function.
func Convert_v1alpha1_LifecycleEventList_To_lifecycle_LifecycleEventList(in *lifecyclev1alpha1.LifecycleEventList, out *lifecycle.LifecycleEventList, s conversion.Scope) error {
	return autoConvert_v1alpha1_LifecycleEventList_To_lifecycle_LifecycleEventList(in, out, s)
}

func autoConvert_lifecycle_LifecycleEventList_To_v1alpha1_LifecycleEventList(in *lifecycle.LifecycleEventList, out *lifecyclev1alpha1.LifecycleEventList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]lifecyclev1alpha1.LifecycleEvent)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_lifecycle_LifecycleEventList_To_v1alpha1_LifecycleEventList is an autogenerated conversion function.
func Convert_lifecycle_LifecycleEventList_To_v1alpha1_LifecycleEventList(in *lifecycle.LifecycleEventList, out *lifecyclev1alpha1.LifecycleEventList, s conversion.Scope) error {
	return autoConvert_lifecycle_LifecycleEventList_To_v1alpha1_LifecycleEventList(in, out, s)
}

func autoConvert_v1alpha1_LifecycleEventSpec_To_lifecycle_LifecycleEventSpec(in *lifecyclev1alpha1.LifecycleEventSpec, out *lifecycle.LifecycleEventSpec, s conversion.Scope) error {
	out.TransitionName = in.TransitionName
	out.BindingNode = in.BindingNode
	return nil
}

// Convert_v1alpha1_LifecycleEventSpec_To_lifecycle_LifecycleEventSpec is an autogenerated conversion function.
func Convert_v1alpha1_LifecycleEventSpec_To_lifecycle_LifecycleEventSpec(in *lifecyclev1alpha1.LifecycleEventSpec, out *lifecycle.LifecycleEventSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_LifecycleEventSpec_To_lifecycle_LifecycleEventSpec(in, out, s)
}

func autoConvert_lifecycle_LifecycleEventSpec_To_v1alpha1_LifecycleEventSpec(in *lifecycle.LifecycleEventSpec, out *lifecyclev1alpha1.LifecycleEventSpec, s conversion.Scope) error {
	out.TransitionName = in.TransitionName
	out.BindingNode = in.BindingNode
	return nil
}

// Convert_lifecycle_LifecycleEventSpec_To_v1alpha1_LifecycleEventSpec is an autogenerated conversion function.
func Convert_lifecycle_LifecycleEventSpec_To_v1alpha1_LifecycleEventSpec(in *lifecycle.LifecycleEventSpec, out *lifecyclev1alpha1.LifecycleEventSpec, s conversion.Scope) error {
	return autoConvert_lifecycle_LifecycleEventSpec_To_v1alpha1_LifecycleEventSpec(in, out, s)
}

func autoConvert_v1alpha1_LifecycleEventStatus_To_lifecycle_LifecycleEventStatus(in *lifecyclev1alpha1.LifecycleEventStatus, out *lifecycle.LifecycleEventStatus, s conversion.Scope) error {
	out.ClaimStatus = lifecycle.LifecycleEventClaimStatus(in.ClaimStatus)
	out.Driver = in.Driver
	out.Sla = (*v1.Time)(unsafe.Pointer(in.Sla))
	return nil
}

// Convert_v1alpha1_LifecycleEventStatus_To_lifecycle_LifecycleEventStatus is an autogenerated conversion function.
func Convert_v1alpha1_LifecycleEventStatus_To_lifecycle_LifecycleEventStatus(in *lifecyclev1alpha1.LifecycleEventStatus, out *lifecycle.LifecycleEventStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_LifecycleEventStatus_To_lifecycle_LifecycleEventStatus(in, out, s)
}

func autoConvert_lifecycle_LifecycleEventStatus_To_v1alpha1_LifecycleEventStatus(in *lifecycle.LifecycleEventStatus, out *lifecyclev1alpha1.LifecycleEventStatus, s conversion.Scope) error {
	out.ClaimStatus = lifecyclev1alpha1.LifecycleEventClaimStatus(in.ClaimStatus)
	out.Driver = in.Driver
	out.Sla = (*v1.Time)(unsafe.Pointer(in.Sla))
	return nil
}

// Convert_lifecycle_LifecycleEventStatus_To_v1alpha1_LifecycleEventStatus is an autogenerated conversion function.
func Convert_lifecycle_LifecycleEventStatus_To_v1alpha1_LifecycleEventStatus(in *lifecycle.LifecycleEventStatus, out *lifecyclev1alpha1.LifecycleEventStatus, s conversion.Scope) error {
	return autoConvert_lifecycle_LifecycleEventStatus_To_v1alpha1_LifecycleEventStatus(in, out, s)
}

func autoConvert_v1alpha1_LifecycleTransition_To_lifecycle_LifecycleTransition(in *lifecyclev1alpha1.LifecycleTransition, out *lifecycle.LifecycleTransition, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_LifecycleTransitionSpec_To_lifecycle_LifecycleTransitionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_LifecycleTransition_To_lifecycle_LifecycleTransition is an autogenerated conversion function.
func Convert_v1alpha1_LifecycleTransition_To_lifecycle_LifecycleTransition(in *lifecyclev1alpha1.LifecycleTransition, out *lifecycle.LifecycleTransition, s conversion.Scope) error {
	return autoConvert_v1alpha1_LifecycleTransition_To_lifecycle_LifecycleTransition(in, out, s)
}

func autoConvert_lifecycle_LifecycleTransition_To_v1alpha1_LifecycleTransition(in *lifecycle.LifecycleTransition, out *lifecyclev1alpha1.LifecycleTransition, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_lifecycle_LifecycleTransitionSpec_To_v1alpha1_LifecycleTransitionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_lifecycle_LifecycleTransition_To_v1alpha1_LifecycleTransition is an autogenerated conversion function.
func Convert_lifecycle_LifecycleTransition_To_v1alpha1_LifecycleTransition(in *lifecycle.LifecycleTransition, out *lifecyclev1alpha1.LifecycleTransition, s conversion.Scope) error {
	return autoConvert_lifecycle_LifecycleTransition_To_v1alpha1_LifecycleTransition(in, out, s)
}

func autoConvert_v1alpha1_LifecycleTransitionList_To_lifecycle_LifecycleTransitionList(in *lifecyclev1alpha1.LifecycleTransitionList, out *lifecycle.LifecycleTransitionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]lifecycle.LifecycleTransition)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_LifecycleTransitionList_To_lifecycle_LifecycleTransitionList is an autogenerated conversion function.
func Convert_v1alpha1_LifecycleTransitionList_To_lifecycle_LifecycleTransitionList(in *lifecyclev1alpha1.LifecycleTransitionList, out *lifecycle.LifecycleTransitionList, s conversion.Scope) error {
	return autoConvert_v1alpha1_LifecycleTransitionList_To_lifecycle_LifecycleTransitionList(in, out, s)
}

func autoConvert_lifecycle_LifecycleTransitionList_To_v1alpha1_LifecycleTransitionList(in *lifecycle.LifecycleTransitionList, out *lifecyclev1alpha1.LifecycleTransitionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]lifecyclev1alpha1.LifecycleTransition)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_lifecycle_LifecycleTransitionList_To_v1alpha1_LifecycleTransitionList is an autogenerated conversion function.
func Convert_lifecycle_LifecycleTransitionList_To_v1alpha1_LifecycleTransitionList(in *lifecycle.LifecycleTransitionList, out *lifecyclev1alpha1.LifecycleTransitionList, s conversion.Scope) error {
	return autoConvert_lifecycle_LifecycleTransitionList_To_v1alpha1_LifecycleTransitionList(in, out, s)
}

func autoConvert_v1alpha1_LifecycleTransitionSpec_To_lifecycle_LifecycleTransitionSpec(in *lifecyclev1alpha1.LifecycleTransitionSpec, out *lifecycle.LifecycleTransitionSpec, s conversion.Scope) error {
	out.Start = in.Start
	out.End = in.End
	out.NodeName = (*string)(unsafe.Pointer(in.NodeName))
	out.NodeSelector = (*core.NodeSelector)(unsafe.Pointer(in.NodeSelector))
	out.AllNodes = (*bool)(unsafe.Pointer(in.AllNodes))
	out.Sla = (*v1.Duration)(unsafe.Pointer(in.Sla))
	out.Driver = in.Driver
	return nil
}

// Convert_v1alpha1_LifecycleTransitionSpec_To_lifecycle_LifecycleTransitionSpec is an autogenerated conversion function.
func Convert_v1alpha1_LifecycleTransitionSpec_To_lifecycle_LifecycleTransitionSpec(in *lifecyclev1alpha1.LifecycleTransitionSpec, out *lifecycle.LifecycleTransitionSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_LifecycleTransitionSpec_To_lifecycle_LifecycleTransitionSpec(in, out, s)
}

func autoConvert_lifecycle_LifecycleTransitionSpec_To_v1alpha1_LifecycleTransitionSpec(in *lifecycle.LifecycleTransitionSpec, out *lifecyclev1alpha1.LifecycleTransitionSpec, s conversion.Scope) error {
	out.Start = in.Start
	out.End = in.End
	out.NodeName = (*string)(unsafe.Pointer(in.NodeName))
	out.NodeSelector = (*corev1.NodeSelector)(unsafe.Pointer(in.NodeSelector))
	out.AllNodes = (*bool)(unsafe.Pointer(in.AllNodes))
	out.Sla = (*v1.Duration)(unsafe.Pointer(in.Sla))
	out.Driver = in.Driver
	return nil
}

// Convert_lifecycle_LifecycleTransitionSpec_To_v1alpha1_LifecycleTransitionSpec is an autogenerated conversion function.
func Convert_lifecycle_LifecycleTransitionSpec_To_v1alpha1_LifecycleTransitionSpec(in *lifecycle.LifecycleTransitionSpec, out *lifecyclev1alpha1.LifecycleTransitionSpec, s conversion.Scope) error {
	return autoConvert_lifecycle_LifecycleTransitionSpec_To_v1alpha1_LifecycleTransitionSpec(in, out, s)
}
