/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	lifecyclev1alpha1 "k8s.io/api/lifecycle/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	applyconfigurationslifecyclev1alpha1 "k8s.io/client-go/applyconfigurations/lifecycle/v1alpha1"
	gentype "k8s.io/client-go/gentype"
	scheme "k8s.io/client-go/kubernetes/scheme"
)

// LifecycleTransitionsGetter has a method to return a LifecycleTransitionInterface.
// A group's client should implement this interface.
type LifecycleTransitionsGetter interface {
	LifecycleTransitions() LifecycleTransitionInterface
}

// LifecycleTransitionInterface has methods to work with LifecycleTransition resources.
type LifecycleTransitionInterface interface {
	Create(ctx context.Context, lifecycleTransition *lifecyclev1alpha1.LifecycleTransition, opts v1.CreateOptions) (*lifecyclev1alpha1.LifecycleTransition, error)
	Update(ctx context.Context, lifecycleTransition *lifecyclev1alpha1.LifecycleTransition, opts v1.UpdateOptions) (*lifecyclev1alpha1.LifecycleTransition, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*lifecyclev1alpha1.LifecycleTransition, error)
	List(ctx context.Context, opts v1.ListOptions) (*lifecyclev1alpha1.LifecycleTransitionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *lifecyclev1alpha1.LifecycleTransition, err error)
	Apply(ctx context.Context, lifecycleTransition *applyconfigurationslifecyclev1alpha1.LifecycleTransitionApplyConfiguration, opts v1.ApplyOptions) (result *lifecyclev1alpha1.LifecycleTransition, err error)
	LifecycleTransitionExpansion
}

// lifecycleTransitions implements LifecycleTransitionInterface
type lifecycleTransitions struct {
	*gentype.ClientWithListAndApply[*lifecyclev1alpha1.LifecycleTransition, *lifecyclev1alpha1.LifecycleTransitionList, *applyconfigurationslifecyclev1alpha1.LifecycleTransitionApplyConfiguration]
}

// newLifecycleTransitions returns a LifecycleTransitions
func newLifecycleTransitions(c *LifecycleV1alpha1Client) *lifecycleTransitions {
	return &lifecycleTransitions{
		gentype.NewClientWithListAndApply[*lifecyclev1alpha1.LifecycleTransition, *lifecyclev1alpha1.LifecycleTransitionList, *applyconfigurationslifecyclev1alpha1.LifecycleTransitionApplyConfiguration](
			"lifecycletransitions",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *lifecyclev1alpha1.LifecycleTransition { return &lifecyclev1alpha1.LifecycleTransition{} },
			func() *lifecyclev1alpha1.LifecycleTransitionList { return &lifecyclev1alpha1.LifecycleTransitionList{} },
			gentype.PrefersProtobuf[*lifecyclev1alpha1.LifecycleTransition](),
		),
	}
}
