/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	lifecyclev1alpha1 "k8s.io/api/lifecycle/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	applyconfigurationslifecyclev1alpha1 "k8s.io/client-go/applyconfigurations/lifecycle/v1alpha1"
	gentype "k8s.io/client-go/gentype"
	scheme "k8s.io/client-go/kubernetes/scheme"
)

// LifecycleEventsGetter has a method to return a LifecycleEventInterface.
// A group's client should implement this interface.
type LifecycleEventsGetter interface {
	LifecycleEvents() LifecycleEventInterface
}

// LifecycleEventInterface has methods to work with LifecycleEvent resources.
type LifecycleEventInterface interface {
	Create(ctx context.Context, lifecycleEvent *lifecyclev1alpha1.LifecycleEvent, opts v1.CreateOptions) (*lifecyclev1alpha1.LifecycleEvent, error)
	Update(ctx context.Context, lifecycleEvent *lifecyclev1alpha1.LifecycleEvent, opts v1.UpdateOptions) (*lifecyclev1alpha1.LifecycleEvent, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, lifecycleEvent *lifecyclev1alpha1.LifecycleEvent, opts v1.UpdateOptions) (*lifecyclev1alpha1.LifecycleEvent, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*lifecyclev1alpha1.LifecycleEvent, error)
	List(ctx context.Context, opts v1.ListOptions) (*lifecyclev1alpha1.LifecycleEventList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *lifecyclev1alpha1.LifecycleEvent, err error)
	Apply(ctx context.Context, lifecycleEvent *applyconfigurationslifecyclev1alpha1.LifecycleEventApplyConfiguration, opts v1.ApplyOptions) (result *lifecyclev1alpha1.LifecycleEvent, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, lifecycleEvent *applyconfigurationslifecyclev1alpha1.LifecycleEventApplyConfiguration, opts v1.ApplyOptions) (result *lifecyclev1alpha1.LifecycleEvent, err error)
	LifecycleEventExpansion
}

// lifecycleEvents implements LifecycleEventInterface
type lifecycleEvents struct {
	*gentype.ClientWithListAndApply[*lifecyclev1alpha1.LifecycleEvent, *lifecyclev1alpha1.LifecycleEventList, *applyconfigurationslifecyclev1alpha1.LifecycleEventApplyConfiguration]
}

// newLifecycleEvents returns a LifecycleEvents
func newLifecycleEvents(c *LifecycleV1alpha1Client) *lifecycleEvents {
	return &lifecycleEvents{
		gentype.NewClientWithListAndApply[*lifecyclev1alpha1.LifecycleEvent, *lifecyclev1alpha1.LifecycleEventList, *applyconfigurationslifecyclev1alpha1.LifecycleEventApplyConfiguration](
			"lifecycleevents",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *lifecyclev1alpha1.LifecycleEvent { return &lifecyclev1alpha1.LifecycleEvent{} },
			func() *lifecyclev1alpha1.LifecycleEventList { return &lifecyclev1alpha1.LifecycleEventList{} },
			gentype.PrefersProtobuf[*lifecyclev1alpha1.LifecycleEvent](),
		),
	}
}
