/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LifecycleEventSpecApplyConfiguration represents a declarative configuration of the LifecycleEventSpec type for use
// with apply.
//
// LifecycleEventSpec defines the binding parameters to claim a transition.
type LifecycleEventSpecApplyConfiguration struct {
	// transitionName refers to a LifecycleTransition object by name.
	TransitionName *string `json:"transitionName,omitempty"`
	// bindingNode identifies a specific Node whose Kubelet can claim the event.
	BindingNode *string `json:"bindingNode,omitempty"`
}

// LifecycleEventSpecApplyConfiguration constructs a declarative configuration of the LifecycleEventSpec type for use with
// apply.
func LifecycleEventSpec() *LifecycleEventSpecApplyConfiguration {
	return &LifecycleEventSpecApplyConfiguration{}
}

// WithTransitionName sets the TransitionName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TransitionName field is set to the value of the last call.
func (b *LifecycleEventSpecApplyConfiguration) WithTransitionName(value string) *LifecycleEventSpecApplyConfiguration {
	b.TransitionName = &value
	return b
}

// WithBindingNode sets the BindingNode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BindingNode field is set to the value of the last call.
func (b *LifecycleEventSpecApplyConfiguration) WithBindingNode(value string) *LifecycleEventSpecApplyConfiguration {
	b.BindingNode = &value
	return b
}
