/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	lifecyclev1alpha1 "k8s.io/api/lifecycle/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// LifecycleEventStatusApplyConfiguration represents a declarative configuration of the LifecycleEventStatus type for use
// with apply.
//
// LifecycleEventStatus reports the current state of the transition claim.
type LifecycleEventStatusApplyConfiguration struct {
	// claimStatus represents the current phase of the event's lifecycle.
	ClaimStatus *lifecyclev1alpha1.LifecycleEventClaimStatus `json:"claimStatus,omitempty"`
	// driver is a copy of the driver name from the LifecycleTransition.
	Driver *string `json:"driver,omitempty"`
	// sla specifies the deadline by which the transition must complete.
	Sla *v1.Time `json:"sla,omitempty"`
}

// LifecycleEventStatusApplyConfiguration constructs a declarative configuration of the LifecycleEventStatus type for use with
// apply.
func LifecycleEventStatus() *LifecycleEventStatusApplyConfiguration {
	return &LifecycleEventStatusApplyConfiguration{}
}

// WithClaimStatus sets the ClaimStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClaimStatus field is set to the value of the last call.
func (b *LifecycleEventStatusApplyConfiguration) WithClaimStatus(value lifecyclev1alpha1.LifecycleEventClaimStatus) *LifecycleEventStatusApplyConfiguration {
	b.ClaimStatus = &value
	return b
}

// WithDriver sets the Driver field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Driver field is set to the value of the last call.
func (b *LifecycleEventStatusApplyConfiguration) WithDriver(value string) *LifecycleEventStatusApplyConfiguration {
	b.Driver = &value
	return b
}

// WithSla sets the Sla field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Sla field is set to the value of the last call.
func (b *LifecycleEventStatusApplyConfiguration) WithSla(value v1.Time) *LifecycleEventStatusApplyConfiguration {
	b.Sla = &value
	return b
}
