/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v1 "k8s.io/client-go/applyconfigurations/core/v1"
)

// LifecycleTransitionSpecApplyConfiguration represents a declarative configuration of the LifecycleTransitionSpec type for use
// with apply.
//
// LifecycleTransitionSpec describes the parameters of a lifecycle transition.
type LifecycleTransitionSpecApplyConfiguration struct {
	// start identifies the initial state of the lifecycle transition.
	Start *string `json:"start,omitempty"`
	// end identifies the desired terminal state of the lifecycle transition.
	End *string `json:"end,omitempty"`
	// nodeName identifies the specific Node that has a Driver capable of
	// reconciling the LifecycleTransition.
	NodeName *string `json:"nodeName,omitempty"`
	// nodeSelector defines which Nodes have Drivers capable of
	// reconciling the LifecycleTransition.
	NodeSelector *v1.NodeSelectorApplyConfiguration `json:"nodeSelector,omitempty"`
	// allNodes indicates that all Nodes are capable of
	// reconciling the LifecycleTransition.
	AllNodes *bool `json:"allNodes,omitempty"`
	// sla specifies the duration by which the transition from Start to End
	// must be completed.
	Sla *metav1.Duration `json:"sla,omitempty"`
	// driver specifies the unique identifier of the lifecycle driver
	// responsible for reconciling this transition.
	Driver *string `json:"driver,omitempty"`
}

// LifecycleTransitionSpecApplyConfiguration constructs a declarative configuration of the LifecycleTransitionSpec type for use with
// apply.
func LifecycleTransitionSpec() *LifecycleTransitionSpecApplyConfiguration {
	return &LifecycleTransitionSpecApplyConfiguration{}
}

// WithStart sets the Start field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Start field is set to the value of the last call.
func (b *LifecycleTransitionSpecApplyConfiguration) WithStart(value string) *LifecycleTransitionSpecApplyConfiguration {
	b.Start = &value
	return b
}

// WithEnd sets the End field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the End field is set to the value of the last call.
func (b *LifecycleTransitionSpecApplyConfiguration) WithEnd(value string) *LifecycleTransitionSpecApplyConfiguration {
	b.End = &value
	return b
}

// WithNodeName sets the NodeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeName field is set to the value of the last call.
func (b *LifecycleTransitionSpecApplyConfiguration) WithNodeName(value string) *LifecycleTransitionSpecApplyConfiguration {
	b.NodeName = &value
	return b
}

// WithNodeSelector sets the NodeSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeSelector field is set to the value of the last call.
func (b *LifecycleTransitionSpecApplyConfiguration) WithNodeSelector(value *v1.NodeSelectorApplyConfiguration) *LifecycleTransitionSpecApplyConfiguration {
	b.NodeSelector = value
	return b
}

// WithAllNodes sets the AllNodes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllNodes field is set to the value of the last call.
func (b *LifecycleTransitionSpecApplyConfiguration) WithAllNodes(value bool) *LifecycleTransitionSpecApplyConfiguration {
	b.AllNodes = &value
	return b
}

// WithSla sets the Sla field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Sla field is set to the value of the last call.
func (b *LifecycleTransitionSpecApplyConfiguration) WithSla(value metav1.Duration) *LifecycleTransitionSpecApplyConfiguration {
	b.Sla = &value
	return b
}

// WithDriver sets the Driver field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Driver field is set to the value of the last call.
func (b *LifecycleTransitionSpecApplyConfiguration) WithDriver(value string) *LifecycleTransitionSpecApplyConfiguration {
	b.Driver = &value
	return b
}
