/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	lifecyclev1alpha1 "k8s.io/api/lifecycle/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// LifecycleTransitionLister helps list LifecycleTransitions.
// All objects returned here must be treated as read-only.
type LifecycleTransitionLister interface {
	// List lists all LifecycleTransitions in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*lifecyclev1alpha1.LifecycleTransition, err error)
	// Get retrieves the LifecycleTransition from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*lifecyclev1alpha1.LifecycleTransition, error)
	LifecycleTransitionListerExpansion
}

// lifecycleTransitionLister implements the LifecycleTransitionLister interface.
type lifecycleTransitionLister struct {
	listers.ResourceIndexer[*lifecyclev1alpha1.LifecycleTransition]
}

// NewLifecycleTransitionLister returns a new LifecycleTransitionLister.
func NewLifecycleTransitionLister(indexer cache.Indexer) LifecycleTransitionLister {
	return &lifecycleTransitionLister{listers.New[*lifecyclev1alpha1.LifecycleTransition](indexer, lifecyclev1alpha1.Resource("lifecycletransition"))}
}
